#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

## CUSTOM ##
HEADER_COLOR="\u001b[35m"
COMMAND_COLOR="\u001b[36m"
NORMAL_COLOR="\u001b[0m"

printf "$HEADER_COLOR"
printf "\nStarting custom install hooks\n\n"
printf "$NORMAL_COLOR"

# Execute all process-config scripts
for program in $(ls | grep --invert-match 'deprecated'); do
    for script in $(find "$program" -name 'process-config.sh'); do
        printf "$COMMAND_COLOR"
        printf "Processing ${program} config\n"
        printf "$NORMAL_COLOR"
        $script
        echo
    done
done

printf "$HEADER_COLOR"
printf "==> All custom install hooks executed successfully\n"
printf "$NORMAL_COLOR"
