#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

## CUSTOM ##
HEADER_COLOR="\u001b[35m"
COMMAND_COLOR="\u001b[36m"
NORMAL_COLOR="\u001b[0m"

printf "$HEADER_COLOR"
printf "\nStarting custom install hooks\n\n"
printf "$NORMAL_COLOR"

# Execute all process-config scripts
find . -type f -name 'process-config.sh' -exec {} \;
printf "$COMMAND_COLOR"
printf "All config files flattened\n"
printf "$NORMAL_COLOR"

printf "$HEADER_COLOR"
printf "\n==> All custom install hooks executed successfully\n"
printf "$NORMAL_COLOR"
