#!/bin/sh
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

CLIENT="i3"

if [[ "$CLIENT" = 'i3' ]]; then
    # Nice programs only if present
    if command -v unclutter; then
        unclutter &
    fi
    if command -v compton; then
        compton -b
    fi

    exec i3
fi
