#!/bin/sh

# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

command -v unclutter > /dev/null && (unclutter --timeout 10 -b) \
    || echo "unclutter not installed" >&2

command -v compton > /dev/null && compton -b \
    || echo "compton not installed" >&2
