#!/bin/sh
#
# Executed by startx (run your window manager from here)

# Args:
#     $1: The Xsession to initialize.

session="$1:-$XORG_CLIENT"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [[ "$1" = 'i3' ]]; then
    if command -v i3 > /dev/null; then
        echo "i3 IS NOT INSTALLED" >&2
    fi

    # Nice programs only if present
    command -v unclutter > /dev/null && (unclutter &) \
        || echo "unclutter not installed" >&2
    command -v compton > /dev/null && compton -b \
        || echo "compton not installed" >&2

    exec i3
fi

if [[ "$1" = 'xfce4' ]]; then
    if command -v xfce-session > /dev/null; then
        echo "Xfce4 IS NOT INSTALLED" >&2
    fi

    exec xfce-session
fi
