#!/bin/sh

# Prevent "intelligent DPI scaling" done by alacritty
# XXX: If there is ever an option to turn this off in alacritty, do this
# instead.
export WINIT_HIDPI_FACTOR=1

# Turn off mouse automatically
command -v unclutter > /dev/null && (unclutter --timeout 10 -b) \
    || echo "unclutter not installed" >&2

# Load Xresources
xrdb ~/.Xresources

# Enable numlock
numlockx on

# Display settings
xset -b b off

# Display Power Management Settings
#         standby suspend off
xset dpms 600     900     1800

# Screen Saver Settings
#      timeout cycle
xset s 300     0
