#!/bin/bash

# Connects to bluetooth device exclusively by name

if [ $# != 1 ]; then
    echo "USAGE: bluetooth-connect DEVICE_NAME"
    echo "       Where DEVICE_NAME is the name of the registered device."
    exit
fi

# Turn on just in case
bluetoothctl power on

DEVICE=$1

ADDRESS=$(bluetoothctl devices | grep $DEVICE | awk '{print $2}')

bluetoothctl connect $ADDRESS
