#!/bin/bash

script_path=$(readlink -f $0)
script_basename=${script_path##*/}
parent_dir=${script_path%/*}
config_file=$parent_dir/config

# reset config file
echo -e "# This script was autogenerated by $script_basename\n" >$config_file

cat $parent_dir/core.i3 >>$config_file

for config in $parent_dir/**/*.i3; do
    echo $config
    cat $config >>$config_file
done
