#!/usr/bin/env sh

# This ctags git rebuild hook was implemented using the guide at
# https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
#
# Author: Tim Pope

set -e
PATH="/usr/local/bin:$PATH"

# The directory to put ctags in
dir=$(git rev-parse --git-dir)

# Remove any tags file that has this process ID
trap 'rm -f "$dir/$$.tags"' EXIT

# Create the tag file
git ls-files | \
  ctags --tag-relative=yes -L - -f"$dir/$$.tags"

# Make the tag file specific to this process ID the general tag file
mv "$dir/$$.tags" "$dir/tags"
