#!/usr/bin/env bash

# Processes the necessary files for my zsh config.
# Author: Eli W. Hunter

# Install zplugin if it's not already installed
if [ ! -d "${HOME}/.zplugin" ]; then
    echo "Installing zplugin"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/mod-install.sh)"
fi

# Creates a bookmark from each line of stdin, assuming all comments have been
# removed. Each line is expected to follow the form "name(1) path(2)".
create_bookmarkes() {
    sed -e 's/#.*//g' |
        grep --invert-match '^$' |
        sed -e 's/~/$HOME/' |
        awk 'NF {print "export "$1"=\""$2"\""}'
}
echo "Creating bookmarks file"
echo '# This script was autogenerated' > ~/.bookmarks.zsh
create_bookmarkes < ~/.bookmarks >> ~/.bookmarks.zsh
