#!/usr/bin/env bash

# Processes the necessary files for my zsh config.
# Author: Eli W. Hunter

# Import my common functions (for converting tildes)
source "$HOME/.functions"

# Removes all comments from the given arguments. The arguments are assumed to
# be consecutive in a single line.
#
# Args:
#    $1: The string that is to have all comments removed.
remove_comments() {
    echo $(echo "$*" | sed -e 's/#.*//g')
}

# Creates a bookmark from a given line, assuming all comments have been removed.
# If the line does not follow the form `name path`, nothing is returned.
#
# Args:
#    $1: The the name to be aliased to.
#    Others: The actual command to be run.
create_bookmark() {
    if [[ "$#" -lt 2 ]]; then
        return 1
    fi
    local BOOKMARK="export ${1}=\"$(_convert_tildes ${2})\""
    echo "$BOOKMARK"
}

# Creates an alias from a given line, assuming all comments have been removed.
# If the line does not follow the form `name command`, nothing is returned.
#
# Args:
#    $1: The the name to be aliased to.
#    Others: The actual command to be run.
create_alias() {
    if [[ "$#" -lt 2 ]]; then
        return 1
    fi
    local ALIAS="alias '${1}'"
    shift
    local ALIAS="${ALIAS}='$@'"
    echo "$ALIAS"
}

# Install antibody if it's not already installed
if [[ -d "/usr/local/bin/antibody" ]]; then
    curl -sL git.io/antibody | sh -s
fi

echo "Bundling all plugins"
antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh

echo "Creating bookmarks file"
echo '# This script was autogenerated' > ~/.bookmarks.zsh
while read LINE; do
    create_bookmark $(remove_comments "$LINE") >> ~/.bookmarks.zsh
done < ~/.bookmarks

echo "Creating aliases file"
echo '# This script was autogenerated' > ~/.aliases.zsh
while read LINE; do
    create_alias $(remove_comments "$LINE") >> ~/.aliases.zsh
done < ~/.aliases
