# BEGIN Oh-my-zsh settings
# Path to your oh-my-zsh installation.
export ZSH="/home/eli/.config/oh-my-zsh"

# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

source $ZSH/oh-my-zsh.sh
# END Oh-my-zsh settings

# Source broad configuration files
source ~/.bookmarks.zsh
source ~/.aliases.zsh
source ~/.functions

# Source my plugins
source ~/.zsh_plugins.sh

# Load pure prompt
autoload -U promptinit; promptinit

# Load completions
autoload -U compinit; compinit
# Completions for kitty
kitty + complete setup zsh | source /dev/stdin

# My custom scripts
export PATH=$PATH:$HOME/.scripts

# Easier history searching
bindkey '^N' down-line-or-beginning-search
bindkey '^P' up-line-or-beginning-search

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi
