# My standard interactive shell config files
source ~/.standard.sh

# Oh-my-zsh for some basic nice config
# Plugins are handled by zplugin
export ZSH="$HOME/.oh-my-zsh"
# Install oh-my-zsh if not already installed
if [ ! -d "$ZSH" ]; then
    git clone https://github.com/robbyrussell/oh-my-zsh.git "$ZSH"
fi
source $ZSH/oh-my-zsh.sh

# Install zplugin if not already installed
if [ ! -d "${HOME}/.zplugin" ]; then
    echo "Installing zplugin"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/mod-install.sh)"
fi

# Load zplugin
module_path+=( "${HOME}/.zplugin/mod-bin/zmodules/Src" )
zmodload zdharma/zplugin 2> /dev/null # ignore random errors
source "${HOME}/.zplugin/mod-bin/zplugin.zsh"

# Pure Prompt
zplugin ice pick"async.zsh" src"pure.zsh"
zplugin light sindresorhus/pure

# More completions
zplugin light zsh-users/zsh-completions
if command -v rustup > /dev/null; then
    rustup completions zsh > ~/.zplugin/completions/_rustup
fi

# Easy extraction
zplugin snippet OMZ::plugins/extract/extract.plugin.zsh
# Colorful man pages
zplugin snippet OMZ::plugins/colored-man-pages/colored-man-pages.plugin.zsh

# Easier history searching
zplugin light zsh-users/zsh-history-substring-search
bindkey 'OA' history-substring-search-up
bindkey 'OB' history-substring-search-down
bindkey '^P'   history-substring-search-up
bindkey '^N'   history-substring-search-down

# All new terminals automatically go to the last working directory (lwd does the same)
zplugin snippet OMZ::plugins/last-working-dir/last-working-dir.plugin.zsh

# Syntax highlighting (this must be done last)
zplugin light zsh-users/zsh-syntax-highlighting

# Load completions
autoload -U compinit; compinit

# Set up pyenv if it exists
if command -v pyenv > /dev/null; then
    eval "$(pyenv init -)"
fi
